ev-flow/quark-engine

- quark/Evaluator/pyeval.py
- quark/Objects/Apkinfo.py
- quark/Objects/BytecodeObject.py
- quark/Objects/RuleObject.py
- quark/Objects/TableObject.py
- quark/Objects/VarabileObject.py
- quark/Objects/XRule.py
- quark/logo.py
- tests/Object/test_variableobject.py
- tests/Object/test_xrule.py
1. add more bytecode instruction into pyeval.py.
2. add dunder method `__repr__` to each object to better represent the state of object.
3. add unit test for XRule.py.
4. follow sphinx docstring style to generate doc automatically in the future.
5. using list.clear() to clean the result from the previous rule to avoid duplicate results in detail report.
6. add logging module to pyeval.py to keep track of the bytecode usage.
7. update version number from v19.10 to v20.01
> Ready to release stable v20.01

- quark/utils/weight.py
When the weight is 0, it will cause an error, because the 0 boundary is not processed
> Fix ValueError by adding 0 boundary in utils/weight.py, issue #60

- README.md
Quark failed to install on a system with Python 3.6 installed. It also failed to run without `git`.
> add quark-engine requirements

- quark/cli.py
Use the following command can directly use the rule sets we provide for analysis
```bash
quark -a test.apk -s
```
Fix the issue #105
> turn -r flag into optional

- quark/utils/regex.py
The regex string for URL validation was probably aimed to be implemented as a **multi-line string**, but it was missing parenthesis/brackets and thus the strings following the initial one (for HTTP check) were ignored.
> multi-line string fix

- quark/utils/output.py
- tests/utils/test_output.py
Quark output crime description twice or more due to the duplication of parent functions. (#119)
Crimes with different bytecodes but the same parent will be output respectively.
Thus, I wrap descriptions with a set in order to filter out the duplicated ones.
> Remove duplicated crime description

- quark/Objects/quark.py
Fix issue #118 .
By @krnick 's advice, move calculations for sums of tatal scores/weighted scores to `show_summary_report` method.
This calculation should not be blocked by thershold.
Thank @krnick a lot!
> Fix score-sum

- quark/Objects/quark.py
Fix issue with DEX files. 
If the file that has to be analyzed is a DEX file, it does not contain a manifest, so it is useless to check for permissions. In fact, this check will only leads to an unwanted behavior: the permission check will fail (even if the permissions are actually requested) and the analysis on that rule will stop (even if the rule is matched for the 100%)
I just edited two lines of code in the `Quark.py` file to skip permissions check if we are analyzing a DEX file.
> Added check to skip permissions check if DEX file

- quark/Evaluator/pyeval.py
fix bug in `AGET_OBJECT` method in `quark/Evaluator/pyeval.py`
This method takes as parameter `instruction`, 
```
print(instruction)
> ['aget-object', 'v9', 'v12', '11']
```
* If register number (v12 in this case) has a certain value (i.e. an integer of 2 digits), with the original code it is taken the wrong register number, as in this case the expected value should be 12, but it is taken 1.
* Index of array (third parameter of instruction) is an integer, so it makes sense to take "all" the value of `instruction[3]` and not `instruction[3][1]`
The edited lines of code permit to get the correct number of register (12, not anymore 1) and the correct index (11 not anymore 1)
Hope this could help :-)
> fix bug in aget-object in quark/Evaluator/pyeval.py

- setup.py
Hi all,
Testing Quark we noticed that, without forcing Click to the latest version (8.0.1) in the Setup.py file, the attribute `flag_value`, inserted to let the options `-s` and `-d` take zero or more arguments, is not working. For this reason, I just changed the Setup.py and Click version. Everything should work correctly now :smile:
> Update setup.py to latest click version

- .travis.yml
- tests/Object/test_analysis.py
- tests/Object/test_quarkrule.py
- tests/test_freshquark.py
- tests/test_report.py
- tests/utils/test_colors.py
- tests/utils/test_graph.py
- tests/utils/test_output.py
- tests/utils/test_pprint.py
- tests/utils/test_regex.py
- tests/utils/test_tools.py
- tests/utils/test_weight.py
Please refer [here](https://github.com/quark-engine/gsoc2021-ShengFengLu/issues/1). For the replacement of Androguard, I want to write tests to improve the test coverage of Quark. This is the **final** PR. (You can find the previous PR [here](https://github.com/quark-engine/quark-engine/pull/182) )
In this PR, I focus on these files.
+ `quark/Objects/analysis.py`
+ `quark/Objects/quarkrule.py`
+ `quark/report.py`
+ `quark/freshquark.py`
+ all seven files in `quark/utils` (colors.py, graph.py, pprint.py, output.py, etc.)
+ **For the existing tests**: Divide them by their test scenarios.
+ **For the new tests**: Add them according to two strategies and the coding guideline discussed in the above issue.
| Files               | # Tests added for normal inputs | # Tests added for error inputs …
> Refactor/enrich the rest of Quark's tests

- quark/Objects/quark.py
- quark/utils/output.py
- tests/utils/test_output.py
The PR adds a new feature that lists references of the parent functions in the rule classification report. (See the text with a yellow underline bellow.)
With this text, the user can see how parent functions interact with each other.
For more details, please refer to issue #191.
1. Add a new function to prepare the data of a rule classification report.
2. Add code to search for cross-references.
**Test Plan**
1. Add tests with test data containing cross-references.
> Show Parent Functions' Cross-References In Rule Classification

- quark/forensic/vt_analysis.py
I have implemented a feature that able to analyze files by query [Virustotal REST API v2](https://developers.virustotal.com/reference)
This feature provides a few functions:
- Analyze single file
- Analyze multiple files (input directory)
- Save the last analysis report as progress for the next analysis
Here is a usage for VTAnalysis 
```python
key_list = { <your virustotal api keys> }
vt = VTAnalysis(key_list)
```
To analyze single file.
```python
result = vt.analyze_single_file("malware.apk")
```
To analyze multiple files.
```python
vt.analyze_multiple_file("apk-malware-sample/")
report = vt.get_reports()
```
Also, you can input the report as an analysis progress
```python
vt.set_progress(report)
```
> The Public API is limited to 500 requests per day and a rate of 4 requests per …
> Add Virustotal analysis

- quark/Objects/baseapkinfo.py
- quark/Objects/methodobject.py
- tests/Object/test_methodobject.py
This PR adds a standard interface for Quark to access an APK.
It is the first step to make the analysis code independent of the core library, Androguard.
This PR provides:
1. BaseApkinfo class, a standard interface that defines how Quark interacts with its core library.
2. MethodObject class, used by the standard interface. It is a replacement for MethodAnalysis class.
**Why is there an additional class, MethodObject ?**
Quark uses MethodAnalysis objects as parameters in most of its files. It's not practical to eliminate the dependency file by file.
A working solution I used here is to replace MethodAnalysis with a Quark-owned class.
The only change to the existing code is adjusting the return values in apkinfo.py. And this change will arrive in the next few PRs.
**Code …
> Add A Standard Interface for Accessing APK Infomation

- quark/Objects/apkinfo.py
- quark/Objects/quark.py
- quark/utils/graph.py
- quark/utils/output.py
- tests/Object/test_apkinfo.py
- tests/utils/test_graph.py
- tests/utils/test_output.py
This PR deprecates all direct calls to MethodAnalysis's method in Quark.
It ensures that all method information used by Quark is from Apkinfo.
It is the second part of making the analysis code independent of the core library, Androguard. (see the first one [here](https://github.com/quark-engine/quark-engine/pull/194  ))
- Add a function lowerfunc in apkinfo.py to get method references.
- Modify the following three files to use lowerfunc instead of get_xref_to.
1. quark.py
2. graph.py
3. output.py
**Test Plans**
- Add a test for lowerfunc in test_apkinfo.py.
> Clean Up the Direct Use of MethodAnalysis

- quark/Objects/apkinfo.py
- quark/Objects/quark.py
- quark/forensic/forensic.py
- quark/utils/graph.py
- tests/Object/test_apkinfo.py
- tests/utils/test_graph.py
- tests/utils/test_output.py
This PR modifies Apkinfo class to implement the standard APK interface.
The goal is to make the analysis code independent to Androguard. It enables the possibility to use other libraries to support Quark analysis.
+ **apkinfo.py**
+ Rename Apkinfo to AndroguardImp
+ Remove the duplicated properties and docstrings.
+ Add a method to convert MethodAnalysis to MethodObject. 
+ **graph.py**
+ Replace access property with access_flags from MethodObject.
+ **quark.py**, **forensic.py**, **test_graph.py** and **test_output.py**
+ Update their imports.
**Test Plans**
+ Ensure the PR passes all existing tests.
> Make Apkinfo implement the standard APK interface

- Pipfile
- Pipfile.lock
- quark/Objects/axmlreader/__init__.py
- quark/Objects/axmlreader/axml_definition
- quark/Objects/quark.py
- quark/Objects/rzapkinfo.py
- quark/cli.py
- quark/forensic/forensic.py
- quark/report.py
- setup.py
- tests/Object/test_apkinfo.py
Quark needs an alternate core library apart from Androguard. Here are the concerns of the Quark team.
1. Androguard is no longer maintained. ([#833](https://github.com/androguard/androguard/issues/833#issue-748070493) from Androguard)
2. Androguard takes up too much memory during analysis. ([#130](https://github.com/quark-engine/quark-engine/issues/130#issue-809891871))
Hence, this PR aims to add a core library based on [Rizin](https://github.com/rizinorg/rizin).
**Why is Rizin?**
Rizin is a fork of the radare2 reverse engineering tools. Here are the advantages.
1. A strong community supports the project.
2. It provides analysis assists that cover the functions of Androguard.
3. It focuses on usability and working features.
**How to enable it?**
**Command Line**
Add an …
> Add a Rizin-based core library

- .github/workflows/smoke_test.yml
- quark/Evaluator/pyeval.py
- quark/Objects/apkinfo.py
- quark/Objects/struct/bytecodeobject.py
- quark/Objects/struct/registerobject.py
- tests/Evaluator/test_pyeval.py
- tests/Object/test_apkinfo.py
This PR aims to add bytecode supports to enhance the tainted analysis. It introduced 227 instructions in total.
The selection principle is to cover all the instructions that make changes to registers.
All of them can be classified into the following five groups.
1. Transfer values between registers. (`move-kind`)
2. Create/access an array. (`new-array-kind`, `filled-array-kind`, `aput-kind`)
3. Perform binary and arithmetic operations.(`unop-kind`, `binop-kind`)
4. Function calls. (`invoke-polymorphic`, `invoke-custom`)
5. Load Java exceptions. (`move-exception`)
However, based on reasonable considerations, the PR excludes several instructions:
1. Instructions for branches - adding them would make the bytecode loader too complex.
2. Instructions for accessing objects - …
> Improve the tainted analysis of Quark

- .travis.yml
**Descriptions**
This PR makes Travis CI set up the latest release of Rizin when it starts a test.
Since there is no official Rizin package on `apt`,
it uses a series of commands to download it via [the Github release page](https://github.com/rizinorg/rizin/releases).
Here are the details:
1. Query the file link to the latest version of Rizin via the release page.
2. Use it to download the latest binaries.
3. Unzip the binaries into /opt/rizin and add the executable rizin to the system variable PATH.
> Update travis.yml to set up Rizin

- .github/workflows/smoke_test.yml
- quark/Evaluator/pyeval.py
- quark/Objects/apkinfo.py
- quark/Objects/interface/baseapkinfo.py
- quark/Objects/quark.py
- quark/Objects/rzapkinfo.py
- quark/Objects/struct/registerobject.py
- tests/Evaluator/test_pyeval.py
- tests/Object/test_apkinfo.py
This PR aims to improve the simulation accuracy of invoke-kind instructions.
It enables the bytecode loader to track the data type of registers.
With the help of types, the tainted analysis can infer the called methods more accurately.
**How does it work**
The RP achieves it by making the following changes.
1. Modify the bytecode loader to record the data type of each register.
2. Add a method to get the class inheritance relation from an APK.
With that information, the Dalvik Bytecode loader can operate the following instructions like a real Dalvik virtual machine.
1. invoke-virtual
2. invoke-interface
3. invoke-super
It performs a lookup procedure defined by the Dalvik doc to find the correct method to call.
1. **quark/Objects/struct/registerobject.py** …
> Enhance the Simulation Accuracy of the Bytecode Loader

- README.md
- Change install instruction in README.md from `pip` to `pip3`
> Update README.md instruction from pip to pip3

- quark/config.py
- quark/evaluator/pyeval.py
Refer to #225 . 
The logging behavior in pyeval.py is now disabled by default. Developers can set a variable in config.py to bring it back.
+ pyeval.py
+ Apply an if-statement to the logger.
+ config.py
+ Add a variable named DEBUG to indicate whether the logger should run.
> Avoid logging messages in the Dalvik Bytecode Loader

- quark/core/rzapkinfo.py
To eliminate the repetitive calculation in the Rizin core library (rzapkinfo.py),
this PR caches the return values of the commonly used attribute, `all_methods`, `permissions`, and `class_hierarchy`.
+ quark/core/rzapkinfo.py
+ Replace decorator, `property` with the cached decorator, `cached_property` in `all_methods`, `permissions`, and `class_hierarchy`.
> Cache commonly used attributes in the Rizin core library

- quark/core/apkinfo.py
This PR uses the built-in function to check the generator value.
The new check can eliminate the repetitive calls in the Androguard core library.
+ quark/core/apkinfo.py
+ Apply the built-in function, [next()](https://docs.python.org/3/library/functions.html#next), to the return value of Androguard API, `AnalyzeAPK.find_methods`.
+ Remove the repetitive calls to Androguard API, `AnalyzeAPK.find_methods`.
> Simplify the generator value check in the Androguard core library

- README.md
- quark/cli.py
- quark/core/parallelquark.py
This PR adds a rule-based parallelization feature to Quark analysis. It allows Quark to scan multiple rules at a time.
**Usage**
Add the option `-j` to set the number of processes that Quark can use for analysis.
(Default is 1, to disable this feature.)
```
quark -a PATH_TO_APK -s -j NUMBER_OF_RULES
```
+ `quark/cli.py`
+ Add the option `-j` as mentioned above.
+ Parallelly start the analysis of each rule before Quark askes the results.
+ `quark/parallelquark.py`
+ A subclass of Quark that handles the parallelization work.
> Parallelize the analysis

- quark/utils/graph.py
- tests/utils/test_graph.py
Please refer to #188.
This PR rewrites the function, wrapper_lookup(), in graph.py to avoid recursion.
+ quark/utils/graph.py
+ Rewrite wrapper_lookup()
**Test plan**
> Remove recursion in graph.py

- .github/workflows/pytest.yml
1. Specify the Rizin version to the latest release, v0.2.1.
2. Cache the generated libraries after building Rizin.
+ pytest.xml
> Fix pytest.xml

- quark/cli.py
- quark/core/struct/ruleobject.py
**Description:**
- Solve #129 
- Prevent Quark from keeping reloading rule files in `cli.py`. Rules now only reload when necessary.
- Multiple rules can save into a single file now by using the `[]` format (JSON array). Of course, Quark can read those rules too.
- `RuleObject` can be created with loaded JSON data now.
**Code changed:**
- cli.py
- ruleobject.py
> Reduce file IO and load rules in array

- quark/cli.py
- quark/core/quark.py
- quark/utils/graph.py
**Descrption:**
- Add output format option to `graph`, the default value is `png`. Users can choose `JSON` as the output format. The `JSON` format is one of the formats provided by Graphviz.
- Related to #134 
- e.g. : `quark -a sample.apk -s -g json` will dump in json format
**Code changed:**
- cli.py
- quark.py
- graph.py
> Add JSON output option to graph

- quark/core/quark.py
Refer to #117 .
Quark can get useful methods calling to APIs even when the rule reached only 60%.
Therefore, the improved Detail report and JSON report are proposed.
In the Native API Combination, a list of calling methods replaces the repeated API information.
> Original
> Improved
---
In JSON report, the key combination is modified to store a list of calling methods.
> Original 
> Improved
**Test plans**
**Future work**
> Display correlated methods even when rules reached only 60%

- quark/core/rzapkinfo.py
- quark/core/struct/ruleobject.py
- quark/utils/tools.py
- tests/core/struct/test_ruleobject.py
- tests/utils/test_tools.py
Refer to  #138 
This PR inserts additional spaces into those APIs that don't have spaces in the arguments. The adjustment happens when Quark loading a JSON rule.
1. quark/utils/tools.py
- add a function to add spaces to the API.
2. quark/core/struct/ruleobject.py
- support API without spaces.
3. quark/core/rzapkinfo.py
- remove the repeated code.
**Test plan**
> Fix Quark rules not matching when no spaces between arguments.

- quark/core/quark.py
- tests/core/json_report_sample.json
- tests/core/test_quark.py
Description
In the feature request in issue #117, there are two PRs (#254, #247) related to it and modified the original report format, including the detail report and JSON report, which caused Jadx and APKLab to fail to read different JSON formats.
Code change
1. quark/core/quark.py
Test plan
Adding a new test in `tests/core/test_quark.py` to ensure that the format must match the sample JSON file `tests/core/json_report_sample.json`.
> Fix json report format

- quark/core/quark.py
- tests/core/json_report_sample.json
> Fix: Remove quotation marks in JSON report

- debian/control
> fix: add missing comma between two depends in debian/control

- Pipfile
Fix #289 
As title, this PR specifies the highest version for each dependency package that Quark is compatible with.
For now, most of them are the latest releases except for prompt-toolkit (due to issue #186 ).
> Specify the highest versions for the dependency packages

- quark/core/axmlreader/__init__.py
- setup.py
Fix #295.
This PR aims to
1. modify `setup.py` to include the missing file, `quark/core/axmlreader/axml_definition`.
2. use [the recommended API](https://setuptools.pypa.io/en/latest/userguide/datafiles.html?highlight=INclude#accessing-data-files-at-runtime)  to access it in the Rizin-based analysis library.
> Fix the missing file in the PyPi package

- quark/core/rzapkinfo.py
Fix #301.
This PR aims to skip those incorrect cross-references provided by Rizin. Therefore, it prevents the library from crashing when searching for mutual parent functions.
**Code  Changes**
+ `quark/core/rzapkinfo.py`
> Fix the Rizin-based library crashing due to incorrect cross-references 

- setup.py
Please refer to #304.
This PR specifies the minimal supported version of [prettytable](https://github.com/jazzband/prettytable) to `1.0.0`.
+ `setup.py`
> Specify the minimal supported version of prettytable

- .github/workflows/pytest.yml
- README.md
- quark/core/quark.py
- quark/core/rzapkinfo.py
- tests/core/test_apkinfo.py
Close #314.
This PR updates the Rizin-based analysis library to work with Rizin v0.3.x. It includes the following changes:
1. Update parsers for Rizin command `isj` and `pdfj`.
2. Replace command `icg` with `icj` since Rizin v0.3.0 removed it.
3. Add more checks to prevent [upstream issues](https://github.com/rizinorg/rizin/issues/2416) crashing Quark.
+ quark/core/quark.py
+ quark/core/rzapkinfo.py
**Test Plans**
All tests passed on Rizin v0.3.x (v0.3.0, v0.3.1, v0.3.2, v0.3.3, and v0.3.4).
> Update the analysis library for Rizin v0.3.x

- quark/radiocontrast.py
**Description:**
Add the "Radiocontrast" feature that allows Quark to generate rules with the native APIs in a specific method.
**Usage:**
Here is the simplest way for using Radiocontrast API.
```python
from quark.radiocontrast import RadioContrast
APK_PATH = "~/apk-malware-sample/Ahmyth.apk"
TARGET_METHOD = "Lahmyth/mine/king/ahmyth/CameraManager;->startUp(I)"
GENERATED_RULE_DIR = "~/generated_rules"
radiocontrast = RadioContrast(
APK_PATH, 
TARGET_METHOD, 
GENERATED_RULE_DIR
)
radiocontrast.rule_generate()
```
**File changed:**
- Add `radiocontrast.py` into `quark-engine/quark/`.
> Add Radiocontrast feature

- quark/core/quark.py
- quark/core/struct/ruleobject.py
- quark/radiocontrast.py
- quark/rulegeneration.py
- quark/script/__init__.py
- quark/script/objection.py
- tests/core/test_quark.py
- tests/script/rules/00068.json
- tests/script/test_objection.py
- tests/script/test_script.py
Please refer to #324 
This PR adds the following 7 Quark script APIs for staged result analysis and objection integration.
1. `Rule(ruleJson)`
2. `runQuarkAnalysis(SAMPLE_PATH, ruleInstance)`
3. `behaviorInstance.hasUrl(none)`
4. `methodInstance.getXrefFrom(none)`
5. `methodInstance.getXrefTo(none)`
6. `Objection(Monitoring IP and port)`
7. `objInstance.hookMethod(methodInstance or string)`
**Test Plans**
> Add Quark Script APIs for staged result analysis and objection integration

- quark/script/__init__.py
- tests/script/test_script.py
Please refer to #324 
This PR adds the following 2 Quark script APIs to detect hard-coded credentials.
1. `behaviorInstance.getParamValues(None)`
2. `quarkResultInstance.getAllStrings(None)`
**Test Plans**
> Add Quark Script APIs to detect hard-coded credentials

- quark/script/__init__.py
- tests/script/test_script.py
Please refer to #324 
This PR adds the following a Quark script APIs to detect hard-coded credentials.
1. `quarkResultInstance.findMethodInCaller(callerMethod, targetMethod)`
I also add three properties in Method class, avoiding using innerObj to obtain the info of the method:
1. className
2. methodName
3. descriptor
**Test Plans**
> Add Quark Script APIs to detect CWE-94

- .github/workflows/pytest.yml
- .github/workflows/smoke_test.yml
- Pipfile
- quark/script/ciphey.py
- quark/script/frida/__init__.py
- quark/script/frida/agent.js
- setup.py
- tests/script/test_ciphey.py
- tests/script/test_frida.py
Please refer to #324.
This PR adds the following two Quark script APIs to detect cleartext storage of sensitive information ([CWE-312](https://cwe.mitre.org/data/definitions/312.html)).
1. `hookMethod(fridaSession, method, overloadFilter, callback, watchArgs)`
2. `checkClearText(inputString)`
**Test Plans**
> Add Quark Script APIs to detect CWE-312

- quark/script/__init__.py
- tests/script/rules/00193.json
- tests/script/test_script.py
Please refer to #324.
This PR adds the following one Quark script APIs to detect SQL injection([CWE-89](https://cwe.mitre.org/data/definitions/89.html)).
1. `behaviorInstance.isArgFromMethod(targetMethod)`
**Test Plans**
> Add Quark Script APIs to detect CWE-89

- README.md
- docs/source/quark_script.rst
* Description: Get arguments from method.
* params: None
* return:  python list containing arguments
This scenario seeks to find exposed methods or functions in the APK file. See [CWE-749](https://cwe.mitre.org/data/definitions/749.html) for more details.
Let's use this [APK](https://github.com/OWASP/MASTG-Hacking-Playground) and the above APIs to show how Quark script find this vulnerability.
First, we design a detection rule `configureJsExecution.json` to spot on behavior using method `setJavascriptEnabled`. Then, we use API `methodInstance.getArguments` to check if it enables JavaScript execution on websites. Finally, we look for calls to method `addJavaScriptInterface` in the caller method. If yes, the APK exposes methods or functions to websites. That causes CWE-749 vulnerability. …
> Update document for Quark Script CWE-749

- docs/source/quark_script.rst
This PR aims to fix the following two errors in the Quark Script document for CWE-749 -
+ missing content of Quark rule `configureJsExecution.json`
+ missing words `Quark Rule:` in the title
**Before**
**After**
> Fix missing words/lines in the Quark Script document

- quark/cli.py
- quark/config.py
- quark/freshquark.py
- tests/test_freshquark.py
Please refer to #380 
This PR includes 3 modified files.
- quark/cli.py
- quark/config.py
- quark/freshquark.py
Test Plans
[ issue comment in #380 ](https://github.com/quark-engine/quark-engine/issues/380#issuecomment-1263815618)
> Fix #380, CLI gives an outdated path to the default ruleset

- README.md
Please refer to #399.
The PR adds the link to the Quark Script case for CWE-780 to README.
+ [CWE-780](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-780-in-android-application-mstg-android-java-apk)
> Add Quark Script for CWE-780 to README

- README.md
- quark/webreport/analysis_report_layout.html
- quark/webreport/generate.py
This PR aims to close Issue #405.
Two modifications did.
1.Fix the typo in the radar chart section in Web Report. Change "radare chart" to "radar chart."
2.Darken the grid lines of the radar chart in the Web Report.
> Fix web report typo and darken radar chart grid lines

- README.md
*   [CWE-020](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-20-in-android-application-diva-apk)  Improper Input Validation 
*   [CWE-089](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-89-in-android-application-androgoat-apk)  Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') 
*   [CWE-094](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-94-in-android-application-ovaa-apk)  Improper Control of Generation of Code ('Code Injection') 
*   [CWE-312](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-312-in-android-application-ovaa-apk)  Cleartext Storage of Sensitive Information 
*   [CWE-319](https://quark-engine.readthedocs.io/en/latest/quark_script.h …
> [#444] Adjust CWE Show Case format in README.md.

- docs/source/quark_script.rst
- quark/script/__init__.py
- tests/script/test_script.py
This scenario seeks to find **Improper Certificate Validation**. See [CWE-295](https://cwe.mitre.org/data/definitions/295.html) for more details.
Let’s use this [APK](https://github.com/hax0rgb/InsecureShop) and the above APIs to show how the Quark script finds this vulnerability.
We use the API `findMethodInAPK` to locate all `SslErrorHandler.proceed` methods. Then we need to identify whether the method `WebViewClient.onReceivedSslError` is overridden by its subclass. 
First, we check and make sure that the `MethodInstance.name` is `onReceivedSslError`, and the `MethodInstance.descriptor` is `(Landroid/webkit/WebView; Landroid/webkit/SslErrorHandler; Landroid/net/http/SslError;)V`.
Then we use the API `MethodInstance.findSuperclassHierarchy` to get the superclass list of the method's …
> [Quark#446] Add quark script case for CWE-295

- docs/source/quark_script.rst
- quark/core/apkinfo.py
- quark/core/interface/baseapkinfo.py
- quark/core/rzapkinfo.py
- quark/script/__init__.py
- tests/conftest.py
- tests/core/test_apkinfo.py
- tests/script/test_script.py
This scenario seeks to find **active debug code** in the APK file. See [CWE-489](https://cwe.mitre.org/data/definitions/489.html) for more details.
Let’s use [allsafe.apk](https://github.com/t0thkr1s/allsafe), [AndroGoat.apk](https://github.com/satishpatnayak/AndroGoat), [pivaa.apk](https://github.com/HTBridge/pivaa), and the above APIs to show how the Quark script finds this vulnerability.
First, we use Quark API `getApplication` to get the application element in the manifest file. Then we use `applicationInstance.isDebuggable` to check if the application element sets the attribute `android:debuggable` to true. If **Yes**, that causes CWE-489 vulnerabilities.
-   **Description**: Get the application element from the manifest file of the target sample.
-   **params**:
1.  samplePath: the …
> Add quark script to detect cwe 489

- docs/source/index.rst
- docs/source/quark_method_reference.rst
- quark/core/quark.py
**The algorithm of find_previous_method**
The find_previous_method method uses a DFS algorithm to collect all 
MethodObjects called by the parent_method and add them to the specified
wrapper. The search starts from the base_method and goes on recursively
until there are no more levels or all candidates have been processed.
``` TEXT
1. Initialize an empty set "visited_methods" if it is not provided.
2. Get a set "method_set" using "self.apkinfo.upperfunc(base_method)".
3. Add "base_method" to the "visited_methods" set.
4. If "method_set" is not None then check if "parent_function" is in "method_set".
- If yes, append "base_method" to "wrapper".
- If no, then iterate through each item in "method_set".
- If the item is in "visited_methods", skip it and continue to the next item.
- If not, …
```
> New document file quark_method_reference.rst and new instruction of find_previous_method in document.

- docs/source/quark_method_reference.rst
find_intersection
=====================
**The algorithm of ``find_intersection``**
The ``find_intersection`` method takes in two sets, ``first_method_set`` and 
``second_method_set``, and finds their intersection using a recursive search algorithm.
Here is the process of ``find_intersection``
1. Check that the input sets are not empty. 
If one of the sets is empty, raise a ValueError.
2. Use the & operator to find the intersection of the two sets. 
If the intersection is not empty, return the resulting set.
3. If the intersection is empty, call the method_recursive_search 
function with the input sets and a specified maximum depth.
4. The method_recursive_search function recursively searches for 
the intersection of the two input sets up to the specified depth 
by splitting the sets into …
> New instruction of find_intersection in document.

- docs/source/quark_script.rst
CWE-23
Detect CWE-23 in Android Application (ovaa.apk and InsecureBankv2.apk )
-----------------------------------------------------------------------
This scenario aims to demonstrate the detection of the **Relative Path Traversal** vulnerability using [ovaa.apk](https://github.com/oversecured/ovaa) and [InsecureBankv2.apk](https://github.com/dineshshetty/Android-InsecureBankv2/releases). See [CWE-23](https://cwe.mitre.org/data/definitions/23.html) for more details.
To begin with, we will create a detection rule named ``accessFileInExternalDir.json`` to identify behavior that accesses a file in an external directory.
Next, we will use ``methodInstance.getArguments()`` to retrieve the file path argument and check whether it belongs to the APK or not. If it does not belong to the APK, the …
> Add quark script for CWE-23 

- README.md
Refer to PR #475
This PR adds the link of the CWE-338 showcase to the README.
- [CWE-338](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-338-in-android-application-pivva-apk)
> Add document link of CWE-338 showcase to the README

- quark/core/apkinfo.py
- quark/core/interface/baseapkinfo.py
- quark/core/parallelquark.py
- quark/core/quark.py
- quark/core/rzapkinfo.py
- quark/evaluator/pyeval.py
- quark/radiocontrast.py
- quark/script/__init__.py
- tests/core/test_apkinfo.py
- tests/core/test_quark.py
- tests/script/test_script.py
- tests/utils/test_graph.py
- tests/utils/test_output.py
Fix #467 .
**Code change**
* quark/core/apkinfo.py
* quark/core/interface/baseapkinfo.py
* quark/core/parallelquark.py
* quark/core/quark.py
* quark/core/rzapkinfo.py
* quark/evaluator/pyeval.py
* quark/radiocontrast.py
* quark/script/__ init __.py
* tests/core/test_apkinfo.py
* tests/core/test_quark.py
* tests/script/test_script.py
* tests/utils/test_graph.py
* tests/utils/test_output.py
> Make find_method match methods without giving the descriptor or class/method names (#467)

- quark/core/apkinfo.py
- quark/core/interface/baseapkinfo.py
- quark/core/rzapkinfo.py
- tests/core/test_apkinfo.py
* **Description:** : This property is used to present all Receiver components defined in AndroidManifest.xml file.
*  **File Changes:** 
*  quark-engine/quark/core/apkinfo.py
*  quark-engine/quark/core/interface/baseapkinfo.py
*  quark-engine/quark/core/rzapkinfo.py
*  quark-engine/tests/core/test_apkinfo.py
> Add property `receivers` to Quark Engine.

- docs/source/quark_method_reference.rst
**The algorithm of check_parameter_on_single_method**
The ``check_parameter_on_single_method`` function checks whether two methods use the same parameter.
Here is the process of ``check_parameter_on_single_method``.
1. Define a method named check_parameter_on_single_method, which takes 5 parameters:
* self: a reference to the current object, indicating that this method is defined in a class
* usage_table: a table for storing the usage of called functions
* first_method: the first API or the method calling the first API
* second_method: the second API or the method calling the second API
* keyword_item_list: a list of keywords used to determine if the parameter meets specific conditions
2. Define a Boolean variable regex, which is set to False by default.
3. Obtain the patterns of …
> Add method reference for check_parameter_on_single_method

- docs/source/quark_script.rst
CWE-88
Detect CWE-88 in Android Application (Vuldroid.apk )
-----------------------------------------------------------------------
This scenario seeks to find **Improper Neutralization of Argument Delimiters in a Command**. See [CWE-88](https://cwe.mitre.org/data/definitions/88.html) for more details.
Let’s use this [APK](https://github.com/jaiswalakshansh/Vuldroid) and the above APIs to show how the Quark script finds this vulnerability.
First, we design a detection rule ``ExternalStringsCommands.json`` to spot on behavior using external strings as commands.
Next, we use Quark API ``quarkResultInstance.findMethodInCaller(callerMethod, targetMethod)`` to check if any APIs in the caller method for string matching. 
If NO, the APK does not neutralize special elements within the argument, …
> Add quark script for CWE-88

- docs/source/quark_script.rst
- quark/script/__init__.py
- tests/script/test_script.py
This scenario seeks to find **Improper Verification of Intent by Broadcast Receiver**. See [CWE-925](https://cwe.mitre.org/data/definitions/925.html) for more details.
Let’s use both two of apks ([InsecureBankv2](https://github.com/dineshshetty/Android-InsecureBankv2) and [AndroGoat](https://github.com/satishpatnayak/AndroGoat)) to show how the Quark script finds this vulnerability.
In the first step, we use the `getReceivers` API to find all `Receiver` components defined in the Android application. Then, we exclude any receivers that are not exported.
In the second step, our goal is to verify the **intentAction** is properly validated in each receiver which is identified in the previous step. To do this, we use the `checkMethodCalls` function.
Finally, if any receiver's **onReceive** …
> Add quark script case for CWE-925.

- setup.py
Refer to #480.
Before the fix, the issue can be reproduce:
```Bash
$ git clone --depth=1 https://github.com/quark-engine/quark-engine && cd quark-engine
$ pip install . && cd ..
$ python -c "import pathlib, quark; print('\n'.join(list(map(str, (pathlib.Path(quark.__file__).parent.parent / 'tests').glob('*')))))"
PYTHON_DIR/lib/python3.8/site-packages/tests/conftest.py
PYTHON_DIR/lib/python3.8/site-packages/tests/__init__.py
PYTHON_DIR/lib/python3.8/site-packages/tests/test_report.py
PYTHON_DIR/lib/python3.8/site-packages/tests/__pycache__
PYTHON_DIR/lib/python3.8/site-packages/tests/test_freshquark.py
```
After the fix, the tests is excluded:
```Bash
$ git clone --depth=1 https://github.com/quark-engine/quark-engine && cd quark-engine
$ pip install . && cd ..
$ python -c "import pathlib, …
```
> Exclude the Quark tests from installation.

- README.md
Refer to PR https://github.com/quark-engine/quark-engine/pull/514
This PR adds the link of the CWE-73 showcase to the README.
* [CWE-73](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-73-in-android-application-ovaa-apk)
>  Add document link of CWE-73 showcase to the README

- docs/source/quark_method_reference.rst
**The algorithm of check_sequence**
The function ``check_sequence`` checks if ``mutual_parent`` calls any first method before any second method. If Yes, ``check_sequence`` records the mapping between ``mutual_parent`` and the matched methods and returns True.
Here is the process of ``check_sequence``.
```
1. Initialize the variable state as False.
2. Iterate the method pairs formed by first_method_list and second_method_list.
3. From mutual_parent, find method calls that call any method in the pair. Then collect them into the list seq_table.
4. Check if the length of seq_table is less than 2.
- If True, continue to the next iteration.
5. Sort seq_table according to the offsets of the method calls. Then name the sorted list as method_list_need_check.
6. Check if the method pair is a …
```
> Add method reference for check_sequence

- docs/source/quark_script.rst
CWE-78
Detect CWE-78 in Android Application (Vuldroid.apk )
-----------------------------------------------------------------------
This scenario seeks to find **Improper Neutralization of Special Elements used in an OS Command**. See [CWE-78](https://cwe.mitre.org/data/definitions/78.html) for more details.
Let’s use this [APK](https://github.com/jaiswalakshansh/Vuldroid) and the above APIs to show how the Quark script finds this vulnerability.
First, we design a detection rule ``ExternalStringsCommands.json`` to spot on behavior using external strings as commands.
Next, we use Quark API ``behaviorInstance.getMethodsInArgs()`` to get the methods that passed the external command.
Then we check if the method neutralizes any special elements found in the argument.
If the neutralization is …
> Add quark script for CWE-78

- docs/source/quark_method_reference.rst
run
=====================
**The algorithm of run**
The function ``run`` checks the APK file at five levels to analyze whether it meets the rules. 
Here is the process of ``run``.
```
1. Clean the results of the previous analysis.
2. Store the 'crime' description in the analysis result
3. Level 1 Check: Permission requested
- Check if the input file is a DEX file. 
- If Yes, set the first item of check_item in rule_obj to True.
- If No, check if the permissions of the APK include the permissions in the rule. 
- If Yes, set the first item of check_item to True.
- If No, the function exits.
4. Level 2 Check: Native API call
- Check if the APK uses any of the two native APIs in the rule.
- If Yes, set the second item of check_item to True and store information about the calls of the two …
```
> Add method reference for run in document

- README.md
- docs/source/quark_script.rst
Refer to PR [#519](https://github.com/quark-engine/quark-engine/pull/519)
This PR adds the link of the CWE-78 showcase to the README
* [CWE-78](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-78-in-android-application-vuldroid-apk)
> Add document link of CWE-78 showcase to the README

- docs/source/quark_method_reference.rst
get_json_report
=====================
**The algorithm of get_json_report**
The function ``get_json_report`` generates a report of the analysis performed on the APK file, in JSON format.
Here is the process of ``get_json_report`` .
```
1. Create a Weight object with the total score and weight from the analysis result.
2. Calculate the threat level with the Weight object and store the result in the variable warning.
3. Loop through a list of threat levels and check if the variable warning contains any of the threat levels.
- If Yes, sets the variable warning to the threat level.
4. Return a report with various pieces of information:
- The MD5 hash of the APK
- The filename of the APK
- The file size of the APK
- The threat level of the APK
- The total score of the analysis result
- The JSON …
```
> Add method reference for get_json_report in document

- docs/source/quark_method_reference.rst
add_table_row
===============
**The algorithm of add_table_row**
The function ``add_table_row`` adds a list to the table.
Here is the process of ``add_table_row``.
```
1. The method add_row is then called with a list of parameters. This list includes:
name: filename of rule in rule_obj
rule_obj.crime: description of quark_analysis's crime in rule_obj
confidence: the number of True values in check_item and multiplying by 20
score: the score in rule_obj
weight: the weight in rule_obj
2. The add_row method takes these parameters and adds them as a new row in the summary_report_table.
```
Here is the flowchart of ``add_table_row``.
**The code of add_table_row**
```python
def add_table_row(self, name, rule_obj, confidence, score, weight):
self.quark_analysis.summary_report_table.add_row(
[ …
```
> Add method reference for ‎add_table_row in document

- docs/source/quark_method_reference.rst
**The algorithm of show_summary_report**
The function ``show_summary_report``‎ generates a summary report.
Here is the process of ``show_summary_report``.
```
1. Calculate confidence by counting occurrences of True in rule_obj.check_item and multiplying it by 20 to get a percentage.
2. Calculate the weight using the confidence value through rule_obj.get_score, and retrieves score and rule_filename from rule_obj.
3. Check if a threshold is provided.
-If true, check if the confidence percentage is greater than or equal to the threshold.
-If true, calls add_table_row with relevant arguments.
-If false, calls add_table_row with relevant arguments.
4. Update the quark_analysis instance by adding the calculated weight and score to weight_sum and score_sum.
```
Here is the flowchart of …
> Add method reference for show_summary_report in document

- docs/source/quark_script.rst
Detect CWE-940 in Android Application (ovaa,Vuldroid)
------------------------------------------------------
This scenario aims to demonstrate the detection of the **Improper Verification of Source of a Communication Channel** vulnerability using [ovaa.apk](https://github.com/oversecured/ovaa) and [Vuldroid.apk](https://github.com/jaiswalakshansh/Vuldroid). See [CWE-940](https://cwe.mitre.org/data/definitions/940.html)  for more details.
To begin with, we create a detection rule named ``LoadUrlFromIntent.json`` to identify behavior that loads url from intent data to the WebView.
Next, we retrieve the methods that pass the url. Following this, we check if these methods are only for setting intent, such as findViewById, getStringExtra, or getIntent.
If **NO**, it could imply that the APK …
> Add quark script for CWE-940

- README.md
Refer to PR [#539](https://github.com/quark-engine/quark-engine/pull/539)
This PR adds the link of the CWE-940 showcase to the README
* [CWE-940](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-940-in-android-application-ovaa-vuldroid)  Improper Verification of Source of a Communication Channel
> Add document link of CWE-940 showcase to the README

- README.md
Refer to PR #535 
This PR adds the link of the CWE-117 showcase to the README
* [CWE-117](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-117-in-android-application-allsafe-apk) Improper Output Neutralization for Logs
> Add document link of CWE-117 showcase to the README

- docs/source/quark_method_reference.rst
show_label_report
===============
**The algorithm of show_label_report**
The function ``show_label_report`` generates a tabular report that summarizes statistical information.
Here is the process of ``show_label_report``.
```
1. Clear label_report_table and initializes label_desc.
2. Iterate through the all_labels dictionary.
3. Calculate the maximum, average, and standard deviation of the confidence values for each label.
4. Check if table_version is max.
- If true, set table header for table_version is max.
- If false, set table header for table_version is not max.
```
Here is the flowchart of ``show_label_report``.
**The code of show_label_report**
```python
def show_label_report(self, rule_path, all_labels, table_version):
"""
Show the report based on label, last column represents max …
```
> Add method reference for show_label_report in document

- Pipfile
- Pipfile.lock
> Fix GitHub security alerts by escalating versions of dependent packages.

- docs/source/quark_method_reference.rst
show_rule_classification
===============================
**The algorithm of show_rule_classification**
The function ``show_rule_classification`` extracts rule classification data, highlighting the links between parent functions and associated crimes. It then displays this data in table, JSON, and graphical formats.
Here is the process of ``show_rule_classification``.
```
1. Call the print_info function to display "Rules Classification".
2. Invoke the get_rule_classification_data function
- Use self.quark_analysis.call_graph_analysis_list and MAX_SEARCH_LAYER as parameters.
- Store the returned rule classification data in the data_bundle variable.
3. Call the output_parent_function_table function to display tables on the console. 
- The first column of the table is "Parent Function", and …
```
> Add method reference for show_rule_classification in the document

- docs/source/quark_method_reference.rst
**The algorithm of wrapper_lookup**
The ``wrapper_lookup`` method finds the method that calls the specified native API under the specified method.
```
1. Create a stack that stores the specified method.
2. While the stack has elements, keep doing steps 3, 4, and 5, otherwise return an empty list.
3. Check if the top element of the stack is visited.
- If YES, pop the top element and continue to the next loop.
- If NO, record the top element as visited.
4. Find methods that the top element calls, and we refer to them as submethods.
5. Check if the specified native API is one of the submethods.
- If YES, return a list containing the top element.
- If NO, push the submethods to the stack except Android APIs.
```
Here is the flowchart of ``wrapper_lookup``.
**The code of wrapper_lookup** …
> Add the method reference for wrapper_lookup to the document

- docs/source/quark_script.rst
Detect CWE-502 in Android Application (pivaa)
------------------------------------------------------
This scenario aims to demonstrate the detection of the **Deserialization of Untrusted Data** vulnerability using [pivaa.apk](https://github.com/htbridge/pivaa).See [CWE-502](https://cwe.mitre.org/data/definitions/502.html)   for more details.
To begin with, we create a detection rule named ``deserializeData.json`` to identify behaviors that deserialize data.
Next, we retrieve the methods that interact with the deserialization API. Following this, we check if there are any of the APIs in ``verificationApis`` are found.
If **NO**, it could imply that the APK deserializes the untrusted data, potentially leading to a CWE-502 vulnerability.
Quark Script CWE-502.py
==========================
The …
> Add quark script for CWE-502

- README.md
Refer to PR [#572](https://github.com/quark-engine/quark-engine/pull/572)
This PR adds the link of the CWE-502 showcase to the README
* [CWE-502](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-502-in-android-application-pivaa)  Deserialization of Untrusted Data
> Add document link of CWE-502 showcase to the README

- docs/source/quark_method_reference.rst
**The algorithm of select_label_menu**
The ``select_label_menu`` method allows users to select labels shown in the radar chart.
```
1. Show a checkbox dialog for label selection.
2. Check if the user cancels the selection.
- If YES, print "Canceled!" and exit.
- If No, continue with the following steps.  
3. Check the number of labels the user selects is within the specified range.
- If YES, return the labels.
- If No, go back to the first step
```
Here is the flowchart of ``select_label_menu``.
**The code of select_label_menu**
```python
def select_label_menu(all_labels, min_labels=5, max_labels=10):
"""
allows user to select label to be shown in radar chart
:param all_labels: all label found on the rules
:param min_labels: min label to be shown on radar chart (default 5)
:param …
```
> Add method reference for select_label_menu

- docs/source/quark_script.rst
Detect CWE-601 in Android Application (ovaa)
------------------------------------------------------
This scenario aims to demonstrate the detection of the **URL Redirection to Untrusted Site** vulnerability using [ovaa.apk](https://github.com/oversecured/ovaa). See [CWE-601](https://cwe.mitre.org/data/definitions/601.html) for more details.
To detect the vulnerability, we need to find all the caller methods of ``startActivity`` API that might receive external input without input validation. The ``findMethodInAPK`` function finds all the methods in the APK file that call the ``startActivity`` API. Next, we examine the arguments of each method to discover the methods receiving external input. If a method receives external input but lacks of proper input validation, the CWE-601 vulnerability …
> Add quark script for CWE-601

- README.md
Refer to PR [#591](https://github.com/quark-engine/quark-engine/pull/591)
This PR adds the link of the CWE-601 showcase to the README
*   [CWE-601](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-601-in-android-application-ovaa)  URL Redirection to Untrusted Site ('Open Redirect')
> Add document link of CWE-601 showcase to the README

- docs/source/quark_method_reference.rst
**The algorithm of get_rule_classification_data**
The ``get_rule_classification_data`` method returns the crimes in the call graph analysis list and the cross-references of their parent functions.
```
1. Collect the crimes in the call graph analysis list.
2. Search for cross-references of their parent functions within the specified depth.
3. Return the results of the two steps above.
```
Here is the flowchart of ``get_rule_classification_data``.
**The code of get_rule_classification_data**
```python
def get_rule_classification_data(call_graph_analysis_list, search_depth):
return _collect_crime_description(
call_graph_analysis_list
), _search_cross_references(call_graph_analysis_list, search_depth)
```
> Add the method reference for get_rule_classification_data

- quark/core/axmlreader/__init__.py
- tests/conftest.py
- tests/core/test_axmlreader.py
> Fix permission analysis in the radare2 core for APKs with UTF-8 encoding

- docs/source/quark_script.rst
Detect CWE-798 in Android Application (ovaa.apk)
-------------------------------------------------------
This scenario seeks to find **hard-coded credentials** in the APK file.
CWE-798 Use of Hard-coded Credentials
====================================
We analyze the definition of CWE-798  and identify its characteristics.
See [CWE-798](https://cwe.mitre.org/data/definitions/798.html)  for more details.
Code of CWE-798 in ovaa.apk
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-798.
Quark Scipt: CWE-798.py
First, we design a detection rule ``findSecretKeySpec.json`` to spot on behavior …
> Optimize the CWE-798 document.

- docs/source/quark_script.rst
This scenario seeks to find **code injection** in the APK file. 
We analyze the definition of CWE-94 and identify its characteristics.
See [CWE-94](https://cwe.mitre.org/data/definitions/94.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-94.
First, we design a detection rule ``loadExternalCode.json`` to spot on behavior using the method ``createPackageContext``. Then, we find the caller method that calls the ``createPackageContext``. Finally, we check if the method ``checkSignatures`` is called in the caller method for verification.
```python
SAMPLE_PATH = "ovaa.apk"
RULE_PATH = …
```
> Fix images in CWE-94 and CWE-926 document

- docs/source/quark_script.rst
This scenario seeks to find **exposed methods or functions** in the APK file. 
We analyze the definition of CWE-749 and identify its characteristics.
See [CWE-749](https://cwe.mitre.org/data/definitions/749.html) for more details.
Code of CWE-749 in MSTG-Android-Java.apk
We use the [MSTG-Android-Java.apk](https://github.com/OWASP/MASTG-Hacking-Playground) sample to explain the vulnerability code of CWE-749.
Quark Scipt: CWE-749.py
First, we design a detection rule ``configureJsExecution.json`` to spot on behavior using the method ``setJavascriptEnabled``. Then, we use the API ``methodInstance.getArguments()`` to check if it enables JavaScript …
> Optimize CWE-749 and CWE-780 document

- docs/source/quark_script.rst
This scenario seeks to find **the improper limitation of a pathname to a restricted directory (‘Path Traversal’)**.
We analyze the definition of CWE-22 and identify its characteristics.
See [CWE-22](https://cwe.mitre.org/data/definitions/22.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-22.
First, we design a detection rule `accessFileInExternalDir.json` to spot behavior accessing a file in an external directory.
Next, we use API `methodInstance.getArguments()` to get the argument for the file path and use `quarkResultInstance.isHardcoded(argument)` to check if the argument is hardcoded into the APK. If No, the argument is from …
> Optimize CWE 22 document

- docs/source/quark_script.rst
This scenario aims to demonstrate the detection of the **Relative Path Traversal** vulnerability.
We analyze the definition of CWE-23 and identify its characteristics.
See [CWE-23](https://cwe.mitre.org/data/definitions/23.html) for more details.
Code of CWE-23 in ovaa.apk
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-23.
Quark Scipt: CWE-23.py
To begin with, we will create a detection rule named ``accessFileInExternalDir.json`` to identify behavior that accesses a file in an external directory.
Next, we will use ``methodInstance.getArguments()`` to retrieve the file path argument and …
> Optimize CWE 23 document

- docs/source/quark_script.rst
This scenario seeks to find **Improper Input Validation** in the APK file.
We analyze the definition of CWE-20 and identify its characteristics.
See [CWE-20](https://cwe.mitre.org/data/definitions/20.html) for more details.
We use the [diva.apk](https://github.com/payatu/diva-android) sample to explain the vulnerability code of CWE-20.
First, we design a detection rule ``openUrlThatUserInput.json``, to spot the behavior of opening the URL that the user inputs. Then, we use API ``behaviorInstance.getMethodsInArgs()`` to get a list of methods that the URL in ``loadUrl`` passes through. Finally, we check if any validation method is in the list. If No, the APK does not validate user input. That causes CWE-20 …
> Optimize the CWE-20 document

- docs/source/quark_script.rst
This scenario seeks to find **hard-coded credentials** in the APK file.
We analyze the definition of CWE-798 and identify its characteristics.
See [CWE-798](https://cwe.mitre.org/data/definitions/798.html) for more details.
Code of CWE-798 in ovaa.apk
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-798.
Quark Scipt: CWE-798.py
First, we design a detection rule ``findSecretKeySpec.json`` to spot on behavior using the method ``SecretKeySpec``. Then, we get all the parameter values that are input to this method. And we parse the AES key out of the parameter values. Finally, we check if the …
> Modify CWE-798 code

- docs/source/quark_script.rst
This scenario seeks to find **External Control of File Name or Path** in the APK file.
We analyze the definition of CWE-73 and identify its characteristics.
See [CWE-73](https://cwe.mitre.org/data/definitions/73.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-73.
Let’s use the above APIs to show how Quark script find this vulnerability.
First, we design a detection rule ``accessFileInExternalDir.json`` to spot behavior accessing a file in an external directory.
Second, we use API ``methodInstance.getArguments()`` to get the argument for the file path and use ``quarkResultInstance.isHardcoded(argument)`` to check if the argument is hardcoded into the APK. If **No**, the argument is from external input. …
> Optimize the CWE-73 document

- docs/source/quark_script.rst
This scenario seeks to find **Improper Neutralization of Special Elements used in an OS Command** in the APK file.
We analyze the definition of CWE-78 and identify its characteristics.
See [CWE-78](https://cwe.mitre.org/data/definitions/78.html) for more details.
We use the [Vuldroid.apk](https://github.com/jaiswalakshansh/Vuldroid) sample to explain the vulnerability code of CWE-78.
First, we design a detection rule `ExternalStringsCommands.json` to spot on behavior using external strings as commands.
Next, we use Quark API `behaviorInstance.getMethodsInArgs()` to get the methods that passed the external command.
Then we check if the method neutralizes any special elements found in the argument.
If the …
> Optimize the CWE-78 document

- docs/source/quark_script.rst
This scenario seeks to find **Cleartext Transmission of Sensitive Information** in the APK file.
We analyze the definition of CWE-319 and identify its characteristics.
See [CWE-319](https://cwe.mitre.org/data/definitions/319.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-319.
Let's use the above APIs to show how the Quark script finds this vulnerability. This sample uses the package Retrofit to request Web APIs, but the APIs use cleartext protocols.
We first design a detection rule ``setRetrofitBaseUrl.json`` to spot on behavior that sets the base URL of the Retrofit instance. Then, we loop through a custom list of cleartext protocol schemes and use API ``behaviorInstance.hasString(pattern, isRegex)`` to …
> Optimize the CWE-319 document

- .github/workflows/pytest.yml
- .github/workflows/smoke_test.yml
> Use MacPorts to install packages for MacOS and fix Codecov errors in CI

- docs/source/quark_script.rst
This scenario seeks to find **Deserialization of Untrusted Data** in the APK file.
We analyze the definition of CWE-502 and identify its characteristics.
See [CWE-502](https://cwe.mitre.org/data/definitions/502.html) for more details.
We use the [pivaa.apk](https://github.com/htbridge/pivaa) sample to explain the vulnerability code of CWE-502.
To begin with, we created a detection rule named ``deserializeData.json`` to identify behaviors that deserialize data.
Next, we retrieve the methods that interact with the deserialization API. Following this, we check if there are any of the APIs in ``verificationApis`` are found.
If **NO**, it could imply that the APK deserializes the untrusted data, potentially leading …
> Optimize the CWE-502 document

- docs/source/quark_script.rst
This scenario seeks to find **the use of weak Hash**.
We analyze the definition of CWE-328 and identify its characteristics.
See [CWE-328](https://cwe.mitre.org/data/definitions/328.html) for more details.
We use the [allsafe.apk](https://github.com/t0thkr1s/allsafe) sample to explain the vulnerability code of CWE-328.
First, we use API ``findMethodInAPK(samplePath, targetMethod)`` to find the method ``MessageDigest.getInstance()`` or ``SecretKeyFactory.getInstance()``. Next, we use API ``methodInstance.getArguments()`` with a list to check if the method uses weak hashing algorithms. If **YES**, that causes CWE-328 vulnerability.
```python
from quark.script import findMethodInAPK
SAMPLE_PATH = "./allsafe.apk" …
```
> Optimize the CWE-328 document

- docs/source/index.rst
- docs/source/quark.core.rst
- docs/source/quark_script_agent.rst
Introducing Quark's new member, the Quark Script Agent, the first AI assistant in the Quark team. This agent enables users to perform analyses using natural language, without the need for programming or scripting expertise, making the process simple and user-friendly.
The Quark Script Agent integrates with LangChain, which utilizes OpenAI's large language models to act as a bridge between natural language and the Quark Script API. LangChain defines the Quark Script API as a tool that large language models can understand and use. This means that users can easily call new analysis APIs using natural language commands by simply adding new tools as needed.
Here's an example of using the Quark Script Agent with the `quarkScriptAgent.py`. This agent can currently detect …
> Add Quark Script Agent in Document

- quark/script/__init__.py
- quark/utils/tools.py
- tests/script/test_script.py
**Description:**
This pull request enhances the getParamValue API, which is responsible for extracting method parameters from smali code provided as strings. The primary focus of this update is to refine the filtering mechanism, ensuring cleaner and more accurate extraction of parameters without including extraneous characters.
Refer to issue #665.
> Improve getParamValue API for More Accurate Parameter Extraction from Smali Code

- docs/source/quark_script.rst
> Use getArguments() instead of getParamValues() in CWE showcases

- docs/source/quark_script.rst
This scenario seeks to find **Improper Output Neutralization for Logs**.
We analyze the definition of CWE-117 and identify its characteristics.
See [CWE-117](https://cwe.mitre.org/data/definitions/117.html) for more details.
We use the [allsafe.apk](https://github.com/t0thkr1s/allsafe) sample to explain the vulnerability code of CWE-117.
First, we design a detection rule ``writeContentToLog.json`` to spot on behavior using the method that writes contents to the log file.
Then, we use ``methodInstance.getArguments()`` to get all parameter values of this method. And we check if these parameters contain keywords of APIs for neutralization, such as ``escape``, ``replace``, ``format``, and ``setFilter``.
If the answer is **YES**, that may result in secret context leakage into the log file, or …
> Optimize the document of Quark Script CWE-117

- docs/source/quark_script.rst
This scenario seeks to find **Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)**.
We analyze the definition of CWE-338 and identify its characteristics.
See [CWE-338](https://cwe.mitre.org/data/definitions/338.html) for more details.
We use the [pivaa.apk](https://github.com/HTBridge/pivaa) sample to explain the vulnerability code of CWE-338.
First, we design a detection rule ``useMethodOfPRNG.json`` to spot on behavior that uses Pseudo Random Number Generator (PRNG). Then, we use API ``methodInstance.getXrefFrom()`` to get the caller method of PRNG. Finally, we use some keywords such as “token”, “password”, and “encrypt” to check if the PRNG is for credential usage.
```python
SAMPLE_PATH = "pivaa.apk"
RULE_PATH = …
```
> Optimize the document of Quark Script CWE-338

- docs/source/quark_script.rst
This scenario seeks to find **active debug code**.
We analyze the definition of CWE-489 and identify its characteristics.
See [CWE-489](https://cwe.mitre.org/data/definitions/489.html) for more details.
We use the [allsafe.apk](https://github.com/t0thkr1s/allsafe) sample to explain the vulnerability code of CWE-489.
First, we use Quark API ``getApplication(samplePath)`` to get the application element in the manifest file. Then we use ``applicationInstance.isDebuggable()`` to check if the application element sets the attribute ``android:debuggable`` to true. If **Yes**, that causes CWE-489 vulnerabilities.
```python
from quark.script import getApplication
SAMPLE_PATH = "allsafe.apk"
if getApplication(SAMPLE_PATH).isDebuggable():
print(f"CWE-489 is detected in {SAMPLE_PATH}.")
```
```TEXT
$ …
```
> Optimize the document of Quark Script CWE-489

- docs/source/quark_script.rst
This scenario seeks to find the **Improper Verification of Source of a Communication Channel** in the APK file.
We analyze the definition of CWE-940 and identify its characteristics.
See [CWE-940](https://cwe.mitre.org/data/definitions/940.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-940.
To begin with, we create a detection rule named `LoadUrlFromIntent.json` to identify behavior that loads URLs from intent data to the `WebView`.
Next, we retrieve the methods that pass the URL. Then, we check if these methods are only for getting the URL, such as `findViewById`, `getStringExtra`, or `getIntent`.
If **YES**, it could imply …
> Optimize the document of Quark Script CWE-940

- docs/source/quark_script.rst
This scenario seeks to find **cleartext storage of sensitive data** in the APK file.
We analyze the definition of CWE-312 and identify its characteristics.
See [CWE-312](https://cwe.mitre.org/data/definitions/312.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-312.
We have designed a [Frida](https://frida.re/) script ``agent.js`` to hook a specified method and get the arguments when the method is called. It can be found in [quark-engine/quark/script/frida](https://github.com/quark-engine/quark-engine/tree/master/quark/script/frida).
To begin with, we hook the method ``putString`` to catch its arguments. Then, we check if …
> Optimize the document of Quark Script CWE-312

- .github/workflows/pytest.yml
- .github/workflows/smoke_test.yml
- Pipfile
- Pipfile.lock
- quark/core/axmlreader/__init__.py
- quark/script/frida/__init__.py
- quark/webreport/generate.py
- tests/webreport/test_generate.py
> Replace importlib_resources with builtin module of Python

- docs/source/quark_script.rst
This scenario seeks to find **hard-coded credentials** in the APK file.
We analyze the definition of CWE-798 and identify its characteristics.
See [CWE-798](https://cwe.mitre.org/data/definitions/798.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-798.
First, we design a detection rule ``findSecretKeySpec.json`` to spot on behavior using the constructor ``SecretKeySpec``. Second, we get all the parameter values from this constructor. Then, we parse the AES key from the parameter values. Finally, we check if the AES key is hardcoded in the APK file. If the answer is **YES**, BINGO!!! We find hard-coded credentials in the APK …
> Optimize the document of Quark Script CWE-798

- docs/source/quark_script.rst
This scenario seeks to find **code injection** in the APK file. 
We analyze the definition of CWE-94 and identify its characteristics.
See [CWE-94](https://cwe.mitre.org/data/definitions/94.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-94.
First, we design a detection rule ``loadExternalCode.json`` to spot on behavior using the method ``createPackageContext``. Then, we find the caller method that calls the ``createPackageContext``. Finally, we check if the method ``checkSignatures`` is called in the caller method for verification.
```python
SAMPLE_PATH = "ovaa.apk"
RULE_PATH = …
```
> Optimize the document of Quark Script CWE-94

- docs/source/quark_script.rst
This scenario seeks to find **the improper limitation of a pathname to a restricted directory (‘Path Traversal’)**.
We analyze the definition of CWE-22 and identify its characteristics.
See [CWE-22](https://cwe.mitre.org/data/definitions/22.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-22.
First, we design a detection rule `accessFileInExternalDir.json` to spot behavior accessing a file in an external directory.
Next, we use API `methodInstance.getArguments()` to get the argument for the file path and use `quarkResultInstance.isHardcoded(argument)` to check if the argument is hardcoded into the APK. If **No**, the argument is …
> Optimize the document of Quark Script CWE-22

- docs/source/quark_script.rst
This scenario aims to demonstrate the detection of the **Relative Path Traversal** vulnerability.
We analyze the definition of CWE-23 and identify its characteristics.
See [CWE-23](https://cwe.mitre.org/data/definitions/23.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-23.
To begin with, we create a detection rule named ``accessFileInExternalDir.json`` to identify behavior that accesses a file in an external directory.
Next, we use ``methodInstance.getArguments()`` to retrieve the file path argument and check whether it belongs to the APK. If it does not belong to the APK, the argument is likely from external input.
Then, we …
> Optimize the document of Quark Script CWE-23

- docs/source/quark_script.rst
This scenario seeks to find **Improper Neutralization of Special Elements used in an OS Command** in the APK file.
We analyze the definition of CWE-78 and identify its characteristics.
See [CWE-78](https://cwe.mitre.org/data/definitions/78.html) for more details.
We use the [Vuldroid.apk](https://github.com/jaiswalakshansh/Vuldroid) sample to explain the vulnerability code of CWE-78.
First, we design a detection rule `ExternalStringsCommands.json` to spot on behavior using external strings as commands.
Next, we use Quark API `behaviorInstance.getMethodsInArgs()` to get the methods that passed the external command.
Then we check if the method neutralizes any special elements in the argument.
If the …
> Optimize the document of Quark Script CWE-78

- .github/workflows/pytest.yml
- docs/source/quark_script.rst
This scenario seeks to find **Improper Neutralization of Input During Web Page Generation (‘Cross-site Scripting’)** in the APK file.
We analyze the definition of CWE-79 and identify its characteristics.
See [CWE-79](https://cwe.mitre.org/data/definitions/79.html) for more details.
We use the [Vuldroid.apk](https://github.com/jaiswalakshansh/Vuldroid) sample to explain the vulnerability code of CWE-79.
First, we design a detection rule ``loadUrlFromIntent.json`` to spot the behavior loading URL from intent data to the WebView instance.
Next, we use API ``quarkResultInstance.findMethodInCaller(callerMethod, targetMethod)`` and ``methodInstance.getArguments()`` to check if the Javascript execution is enabled in …
> Optimize the document of Quark Script CWE-79

- docs/source/quark_script.rst
This scenario seeks to find **Argument Injection** in the APK file.
We analyze the definition of CWE-88 and identify its characteristics.
See [CWE-88](https://cwe.mitre.org/data/definitions/88.html) for more details.
We use the [vuldroid.apk](https://github.com/jaiswalakshansh/Vuldroid) sample to explain the vulnerability code of CWE-88.
Let‘s use the above APIs to show how the Quark script finds this vulnerability.
First, we design a detection rule ``ExternalStringsCommands.json`` to spot on behavior using external strings as commands.
Next, we use Quark API ``behaviorInstance.getMethodsInArgs()`` to get the methods that passed the external command.
Then we check if the method neutralizes any special elements in the argument.
If the neutralization is not complete, then it may cause …
> Optimize the document of Quark Script CWE-88

- docs/source/quark_script.rst
This scenario seeks to find **Cleartext Transmission of Sensitive Information** in the APK file.
We analyze the definition of CWE-319 and identify its characteristics.
See [CWE-319](https://cwe.mitre.org/data/definitions/319.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-319.
Let’s use the above APIs to show how the Quark script finds this vulnerability. This sample uses the package `Retrofit` to request Web APIs, but the APIs use cleartext protocols.
We first design a detection rule `setRetrofitBaseUrl.json` to spot on behavior that sets the base URL of the Retrofit instance. Then, we loop through a custom list of cleartext protocol schemes and use API `behaviorInstance.hasString(pattern, isRegex)` to …
> Optimize the document of Quark Script CWE-319

- docs/source/quark_script.rst
This scenario seeks to find **Use of a Broken or Risky Cryptographic Algorithm** in the APK file.
We analyze the definition of CWE-327 and identify its characteristics.
See [CWE-327](https://cwe.mitre.org/data/definitions/327.html) for more details.
We use the [InjuredAndroid.apk](https://github.com/B3nac/InjuredAndroid) sample to explain the vulnerability code of CWE-327.
We first design a detection rule `useOfCryptographicAlgo.json` to spot on behavior using cryptographic algorithms. Then, we use API `behaviorInstance.hasString(pattern, isRegex)` with a list to check if the algorithm is risky. If **YES**, that may cause the exposure of sensitive data.
```python …
```
> Optimize the document of Quark Script CWE-327

- docs/source/quark_script.rst
This scenario seeks to find the **Use of Weak Hash**.
We analyze the definition of CWE-328 and identify its characteristics.
See [CWE-328](https://cwe.mitre.org/data/definitions/328.html) for more details.
We use the [allsafe.apk](https://github.com/t0thkr1s/allsafe) sample to explain the vulnerability code of CWE-328.
First, we use API `findMethodInAPK(samplePath, targetMethod)` to find the method `MessageDigest.getInstance()` or `SecretKeyFactory.getInstance()`. Next, we use API `methodInstance.getArguments()` with a list to check if the method uses weak hashing algorithms. If **YES**, that causes CWE-328 vulnerability.
```python
from quark.script import findMethodInAPK
SAMPLE_PATH = "./allsafe.apk" …
```
> Optimize the document of Quark Script CWE-328

- docs/source/quark_script.rst
This scenario seeks to find **Deserialization of Untrusted Data** in the APK file.
We analyze the definition of CWE-502 and identify its characteristics.
See [CWE-502](https://cwe.mitre.org/data/definitions/502.html) for more details.
We use the [pivaa.apk](https://github.com/htbridge/pivaa) sample to explain the vulnerability code of CWE-502.
To begin with, we created a detection rule named ``deserializeData.json`` to identify behaviors that deserialize data.
Next, we retrieve the methods that interact with the deserialization API. Following this, we check if the methods match any APIs for verifying data.
If **NO**, it could imply that the APK deserializes the untrusted data, potentially leading to a CWE-502 …
> Optimize the document of Quark Script CWE-502

- docs/source/quark_script.rst
This scenario seeks to find **Generation of Predictable IV with CBC Mode** in the APK file.
We analyze the definition of CWE-329 and identify its characteristics.
See [CWE-329](https://cwe.mitre.org/data/definitions/329.html) for more details.
We use the [InsecureBankv2.apk](https://github.com/dineshshetty/Android-InsecureBankv2) sample to explain the vulnerability code of CWE-329.
To begin with, we created a detection rule named ``initializeCipherWithIV.json`` to identify behaviors that initialize a cipher object with IV. Then, we use API `behaviorInstance.getParamValues()` to check if the cipher object uses CBC mode.
Finally, we use API ``behaviorInstance.isArgFromMethod(targetMethod)``  to check if any …
> Add Quark script showcase of detecting CWE-329

- docs/source/quark_script.rst
This scenario seeks to find **Improper Validation of Certificate with Host Mismatch**.
We analyze the definition of CWE-297 and identify its characteristics.
See [CWE-297](https://cwe.mitre.org/data/definitions/297.html) for more details.
We use the [pivaa.apk](https://github.com/htbridge/pivaa) sample to explain the vulnerability code of CWE-297.
First, we use API ``findMethodImpls(samplePath, targetMethod)`` to locate the method that implements the hostname verification, which verifies the hostname of a certificate.
Next, we use API ``isMethodReturnAlwaysTrue(samplePath, targetMethod)`` to check if the method always returns true.
If the answer is **YES**, the method does not check the certificate of the host properly, which may cause CWE-297 vulnerability.
```python
from quark.script …
```
> Add Quark script showcase of detecting CWE-297

- .github/workflows/github-release-draft.yml
- .github/workflows/github-release-issue-pr.yml
- .github/workflows/pythonpublish.yml
> Adjust CI trigger for GitHub release and PyPI release

- docs/source/quark_script.rst
- quark/core/interface/baseapkinfo.py
- quark/script/__init__.py
- tests/conftest.py
- tests/core/test_apkinfo.py
- tests/script/test_script.py
The following three APIs are added to detect [CWE-359](https://cwe.mitre.org/data/definitions/359.html):
+ Description: Get provider elements from the manifest file.
+ return: python list containing provider elements 
+ Description: Get provider elements from the manifest file of the target sample.
+ params:
1. samplePath: the file path of target sample
+ return: python list containing provider elements 
+ Description: Check if the provider element set ``android:exported=true``.
+ params: none
+ return: True/False
> Add Quark Script APIs to detect CWE-359
