ev-flow/quark-engine

docs/source/index.rst

fix typo in index.rst

---

quark/main.py

as title
need to same with next_list2

use list extend instead of directly assigning

---

quark/main.py

prevent some functions from looking for themselves

---

README.md

- update video
- update command line using click
- updated results photos
- use "summary report" rather than "easy report"

Update command interface and the result of videos and photos, fixes #2

---

docs/source/install.rst

Update quark command line usage.

---

quark/Objects/RuleObject.py

When confidence is 0, the weighting score should be 0

---

quark/Objects/RuleObject.py

When confidence is 0, the weighting score should be 0 (#27)

---

quark/Objects/RuleObject.py
tests/Object/test_xrule.py

add test for find_previous_method method

add unit test for xrule

---

quark/Objects/xrule.py

1. fixes #50.
2. Reduce the nested if conditionals to improve readability.
3. Replace the string concatenation with f-string.

fixes bug issue in #50

---

quark/Evaluator/pyeval.py
quark/Objects/apkinfo.py
quark/Objects/xrule.py

Make empty list comparisons more Pythonic, fixes #53

---

Pipfile
Pipfile.lock
quark/Objects/xrule.py
quark/cli.py
quark/utils/tools.py
tests/utils/test_tools.py

Add feature of show json report and the report can be output as json file
Show json report
```
$ quark -a sample/14d9f1a92dd984d6040cc41ed06e273e.apk \
-r rules/ \
--jreport
```
Out put report as json file
```
$ quark -a sample/14d9f1a92dd984d6040cc41ed06e273e.apk \
-r rules/ \
--jreport \
-o report/report.json
```

Add json report

---

README.md
docs/source/index.rst
docs/source/install.rst
docs/source/install_index.rst
docs/source/testing.rst

I was aware that some typos in the commands of README. This pull request fixes them and update the corresponding output result.
Bonus change: re-structure the heads of the document.
**PR made with love in PyCon TW 2020 sprint event!!**

Update readme for running commands

---

quark/Objects/quark.py
tests/Object/test_quark.py

Bugfix to #86, also with testcase with json report generator.
@krnick please take review.

Bugfix in saving json format report

---

Pipfile
quark/freshquark.py
setup.py

Download rules from github rules: https://github.com/quark-engine/quark-rules

add feature of freshquark to download rules

---

quark/Objects/apkinfo.py
quark/forensic/forensic.py
tests/forensic/test_forensic.py

1. JSON report support ghidra with hex output of function call
2. More test case and doc with forensic module

ready for release of v21.02.1

---

quark/cli.py

More clear and concise help information
List Android API with classes, methods and descriptors

New improvements to the command line

---

quark/Objects/quark.py
quark/Objects/quarkrule.py
quark/rules/sendLocation_SMS.json
tests/Object/test_ruleobject.py

refactor the rule design to more simple

---

quark/cli.py

Thanks for issue #147 for pointing out this problem.

Update cli.py -i option to point out the usage of Android API

---

README.md
quark/Evaluator/pyeval.py
quark/Objects/apkinfo.py
quark/cli.py
quark/config.py
quark/freshquark.py
tests/Object/test_apkinfo.py

1. Add command line options to display methods including native, custom and all methods.
2. Delete the automatic check for rules updates in the CLI.
3. Do not delete the existing quark-rules git directory.
4. Promote honeynet and GSoC.
5. Quark will be added to Kali Linux in the near future.

prepare to release v21.3.4

---

quark/Objects/analysis.py
quark/Objects/quark.py
quark/Objects/quarkrule.py
quark/cli.py
quark/rules/sendLocation_SMS.json
setup.py
tests/Object/test_ruleobject.py

Hi all,
this merge request follows the #165   
here the code modified
* used black tool as suggested by @krnick,
* substitute "score" with "confidence" variables/strings as discussed in merge request #165
Hope everything works fine :smile:

 Creation of option to print Report based on Label Rules  (pt 2)

---

quark/Objects/analysis.py
quark/Objects/quark.py
quark/cli.py

Hi all,
This merge request follows the #167
I cleaned my previous commits from whitespaces errors. Moreover, the code now follows the latest version of the master branch.
Hope everything works fine now :smile:

Choose one rule or label to be analyzed in summary or detailed output + more Rules info in output (pt 2)

---

README.md
quark/cli.py

Hi all,
I made just some small changes that can maybe help users to understand how to properly use the `summary` and `detail` options.
In particular, I updated:
-  The help, trying to explain the possible usage of the `-s `and `-d` options
- The README.md, to specify how the two options can be used
I hope these clarifications can be appreciated :smile:

Updated help and README for summary and detail

---

quark/cli.py
quark/utils/graph.py
setup.py

Hi all,
team @cryptax (me, @Dil3mm3 , @3aglew0) is still working :muscle: 
this merge request follows the #171 
according to our discussion I edit the code to obtain the following
* change description in the click help menu
* modify the layout of the radar chart, mainly
* add title to graph
* increase font-size (set as parameter)
* move legend close to graph
* Split the logic in cli.py, in particular
* graph is managed in graph.py and now chose of parameters is more flexible (font size, min and max labels...) 
* to make the code in cli.py shorter and easier to be read I moved the management of the menu (which allows to select label) in utils/graph.py introducing function *select_label_menu*, also in this case I believe code is more flexible and easier for management
Let me know what you …

NEW FEATURE FOR MALWARE COMPARISON BASED ON LABEL (PT 2)

---

Pipfile
Pipfile.lock
setup.py

fix prompt-toolkit version

---

README.md

1. Add a section for the upcoming unstable feature.
2. Add a description and an example for the Rizin-based core library.

Update README.md for the upcoming unstable feature

---

Pipfile
Pipfile.lock
README.md
setup.py

Remove the version requirement for Click

---

quark/forensic/vt_analysis.py

- Add recursive traverse directories to vt_analysis.py

Add recursive traverse directories to vt_analysis

---

quark/cli.py

Fix threshold filtering in the detailed mode.

---

quark/cli.py
quark/freshquark.py

**Description:**
- Add hints when using `freshquark` and specifying rules.
- Reference to #237 
**Code changed:**
- cli.py
- freshquark.py

add hint when rules not found

---

quark/cli.py

Close #258 .
The PR rewrites the rule-loading logic to ensure that Quark scans with the correct rules.
**Code change**
+ `quark/cli.py`
- Move all code sections for rule loading to the beginning of the entry point.
- Simplify the code for collecting labels from the loaded rules.
**Test plan**

Fix Quark failing to scan with specific rule set

---

.github/workflows/smoke_test.yml
quark/evaluator/pyeval.py

Fix: Update all the used registers after simulating the invoke-kind instruction.

---

README.md

Indicate the compatible Rizin versions in the README

---

.github/workflows/smoke_test.yml

Fix #319.
This PR updates the numbers of 100% matched rules recorded in `smoke_test.yml`.
+ For Ahmyth.apk, the value has been increased from 19 to 22.
+ For other samples, the value is not changed.

Update smoke test for the BladeHawk ruleset

---

.github/workflows/smoke_test.yml

Fix #327.
This PR updates the numbers of 100% matched rules recorded in smoke_test.yml.
| Samples used by the smoke test                                      | Old values | New values |
|----------------------------------------------|------------|------------|
| Ahmyth.apk                                   | 22         | 28         |
| 13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk | 11         | 17         |
| 14d9f1a92dd984d6040cc41ed06e273e.apk         | 21         | 27         |

Update smoke test for the SMS message ruleset

---

.github/workflows/smoke_test.yml

Fix #340.
This PR updates the numbers of 100% matched rules recorded in smoke_test.yml.
| Samples used by the smoke test                                      | Old values | New values |
|----------------------------------------------|------------|------------|
| Ahmyth.apk                                   | 28         | 33         |
| 14d9f1a92dd984d6040cc41ed06e273e.apk         | 27         | 33         |

Update smoke test for the audio recording ruleset

---

.github/workflows/smoke_test.yml

Fix #342.
This PR updates the numbers of 100% matched rules recorded in smoke_test.yml.
| Samples used by the smoke test                                      | Old values | New values |
|----------------------------------------------|------------|------------|
| Ahmyth.apk                                   | 33         | 35         |
| 13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk |17| 19|
| 14d9f1a92dd984d6040cc41ed06e273e.apk         | 33| 36|

Update smoke test for the contact info accessing ruleset

---

quark/cli.py

Please refer to #346.
This PR adds the ability to load rules from the subfolders of the given path.
**Code Change**
+ cli.py

Support loading rules recursively

---

setup.py

Edit author

---

.github/workflows/pytest.yml

Specify CI to use Meson 0.62.0

---

README.md

Close #366.
This PR aims to do the following improvements on README.
**1 - Clean up outdated information**
+ Change the link of social media to Quark's Twitter account. (ac44d10c347a37e27ae248176cc7e107545dbf94)
+ Fix the wrong commands in the Detail Report section. (4b648e308d2621921837d2333eee944b00be29b1)
+ Add an introduction for Detection Rules Viewer. (233901874caa1b6edd63414c2e0b211c2240141a)
**2 - Simplify the content**
+ Move the screenshots into the collapsible sections. (54cc4e15263d837e85efe5d26df5277718cf74d1)
+ Simplify the description of getting the latest rules. (f29a3226bc764b3f40f7d83eab539b578e9dac6d)
**3 - Adjusting the layout**
+ Add an overview of all the features. (24e2838c519564274f774d863dfbd9d20f294caf)
+ Rearrange the introduction of each report …

Update README for the recently released features

---

README.md

Add Quark Script CWE-532 to README.
*   [CWE-532](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-532-in-android-application-dvba-apk)

Add Quark Script CWE-532 to README

---

README.md
quark/cli.py
quark/utils/graph.py
quark/webreport/analysis_report_layout.html

This PR fix #409, not only typo on web report but also in other functions.
I update the screenshot in README as well.

Fix typo found on Quark web report

---

.github/workflows/smoke_test.yml
quark/core/quark.py
setup.py

This PR is related to Issue #437.
We remove dependency kaleido temporarily to avoid failure in build test.

Remove dependency kaleido temporarily

---

README.md

Refer to PR #458 
This PR adds the link of the CWE-489 showcase to the README.
+ [CWE-489](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-489-in-android-application-allsafe-apk-androgoat-apk-pivaa-apk)

Add document link of CWE-489 showcase to the README

---

README.md

Refer to PR #460 
This PR adds the link of the CWE-22 showcase to the README.
-   [CWE-22](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-22-in-android-application-ovaa-apk-and-insecurebankv2-apk)

Add document link of CWE-22 showcase to the README

---

README.md

Refer to PR [#476](https://github.com/quark-engine/quark-engine/pull/476)
This PR adds the link of the CWE-23 showcase to the README.
* [CWE-23](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-23-in-android-application-ovaa-apk-and-insecurebankv2-apk)

Add document link of CWE-23 showcase to the README

---

docs/source/conf.py

Fix the failure of building documents in readthedocs

---

docs/source/quark_method_reference.rst

_evaluate_method
=====================
**The algorithm of _evaluate_method**
The ``_evaluate_method`` method evaluates the execution of opcodes in the target method and returns a matrix representing the usage of each involved register. The method takes one parameter, method, which is the method to be evaluated.
Here is the process of ``_evaluate_method`` .
```
1. Create a PyEval object with the apkinfo attribute of the instance. PyEval is presumably
a class that handles the evaluation of opcodes.
2. Loop through the bytecode objects in the target method by calling the get_method_bytecode 
method of the apkinfo attribute.
3. Extract the mnemonic (opcode), registers, and parameter from the bytecode_obj and create 
an instruction list containing these elements.
4. Convert all elements of the …
```

Add method reference for _evaluate_method in document 

---

.github/workflows/pytest.yml
.travis.yml

remove deprecated codecov package

---

.github/workflows/smoke_test.yml

**File changed**
- .github/workflows/smoke_test.yml

Fix smoke test error due to image macos 10 being deprecated.

---

README.md

Refer to PR https://github.com/quark-engine/quark-engine/pull/500
This PR adds the link of the CWE-925 showcase to the README.
- [CWE-925](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-925-in-android-application-insecurebankv2-androgoat)

Add document link of CWE-925 showcase to the README

---

docs/source/quark_method_reference.rst

check_parameter
==================
**The algorithm of check_parameter**
The function ``check_parameter`` is designed to check for the usage of the same parameter between two methods.
Here is the process of ``check_parameter``.
```
1. Check if parent_function, first_method_list or second_method_list is None. 
- If True, raise a TypeError exception.
2. Check if the keyword_item_list parameter exists and has elements.
- If False, set keyword_item_list to None.
3. Initialize the state variable to False.
4. Evaluate the opcode of the parent_function by calling self._evaluate_method and store the result to usage_table. 
5. Iterate through the combinations of methods from the first_method_list and second_method_list. 
6. Call self.check_parameter_on_single_method with usage_table to check if the …
```

Add method reference of check_parameter

---

docs/source/quark_method_reference.rst

check_parameter_values
==========================
**The algorithm of check_parameter_values**
The function ``check_parameter_values`` is designed to check if the parameter values in the source string match the specified patterns and keywords. Then it collects the matched strings into a set and return it.
Here is the process of ``check_parameter_values``.
1. Create an empty set matched_string_set.
2. Use tools.get_parenthetic_contents to extract the content that matches each pattern in the pattern_list from the source_str. Store the results in the parameter_strs list.
3. Use zip to pair up the parameter_strs and keyword_item_list and iterate over them.
4. For each pairing of parameter_str and keyword_item, perform the following operations:
- Check if keyword_item is not None.
- For each …

Add method reference of check_parameter_values

---

.github/workflows/pytest.yml
.github/workflows/smoke_test.yml

Install packages with pip instead of Setuptools in CI

---

docs/source/quark_method_reference.rst
docs/source/quark_script.rst

Detect  CWE-73 in Android Application (ovaa.apk)
---------------------------------------------------
This scenario seeks to find **External Control of File Name or Path**. See [CWE-73](https://cwe.mitre.org/data/definitions/73.html)  for more details.
First, we design a detection rule ``accessFileInExternalDir.json`` to spot behavior accessing a file in an external directory.
Second, we use API ``methodInstance.getArguments()`` to get the argument for the file path and use ``quarkResultInstance.isHardcoded(argument)`` to check if the argument is hardcoded into the APK. If No, the argument is from external input.
Finally, we use Quark API ``quarkResultInstance.findMethodInCaller(callerMethod, targetMethod)``  to check if any APIs in the caller method for opening files. If **YES**, the APK …

Add Quark Script CWE-73

---

README.md
docs/source/quark_script.rst

Rivise the description of CWE-78

Rivise the description of CWE-78

---

docs/source/quark_method_reference.rst

generate_json_report
===============
**The algorithm of generate_json_report**
The function ``‎generate_json_report`` generates a JSON report based on the information extracted from the ruleobject instance .
Here is the process of ``generate_json_report``.
```
1. Calculate confidence percentage by counting the number of True values in check_item and multiplying by 20. Store the confidence value.
2. Count the True values in check_item and store the count as conf. Use conf to calculate the weight of the rule using the get_score method.
3. Assign the score attribute's value to the score variable.
4. Check the first item in check_item.
　　-If True, assign the permission attribute to permissions.
　　-Otherwise, assign an empty list.
5. Check the second item in check_item.
　　-If True, populate …
```

Add method reference for ‎generate_json_report in document 

---

.readthedocs.yaml

Add .readthedocs.yaml for Readthedocs

---

docs/source/quark_method_reference.rst
docs/source/quark_script.rst

Detect CWE-117 in Android Application (allsafe.apk)
-------------------------------------------------------------
This scenario seeks to find **Improper Output Neutralization for Logs**. See [CWE-117](https://cwe.mitre.org/data/definitions/117.html) for more details.
Let’s use this [APK](https://github.com/t0thkr1s/allsafe) and the above APIs to show how the Quark script finds this vulnerability.
First, we design a detection rule ``writeContentToLog.json`` to spot on behavior using the method that writes contents to the log file.
Then, we use ``behaviorInstance.getParamValues()`` to get all parameter values of this method. And we check if these parameters contain keywords of APIs for neutralization, such as escape, replace, format, and setFilter.
If the answer is **YES**, that may result …

Add quark script for CWE-117

---

docs/source/index.rst
docs/source/visual_quark_script_program.rst

Quark Script is a powerful tool for detecting and analyzing mobile security. However, it can be complex and challenging for user who are not familiar with programming. To overcome this challenge, we are pleased to announce our plan to develop a visual programming tool that simplifies the Quark Script organization process, making it easy for anyone to organize Quark Script using a simple UI interface.
We aim to make Quark Script programming accessible to everyone and remove the barriers that often come with traditional programming languages. So we design a new visual tool for Quark Script organization. It would be more intuitive, time-saving, and effort-saving for users, even if they are not familiar with programming.
The initial draft of the web design is as below.
Design by: @Commuter95

Visual Quark Scripts Program: Web design layout

---

docs/source/visual_quark_script_program.rst

Fix image link error in document of Visual Quark Script

---

docs/source/quark_method_reference.rst

**The algorithm of show_detail_report**
The function ``show_detail_report`` prints a report summarizing the result of the five-level check and the confidence of the APK.
Here is the process of ``show_detail_report``.
```
1. Calculate the confidence of the APK by multiplying the number of passed levels by 20.
2. Check if the APK passed level 1.
- If passed, show the match permissions.
3. Check if the APK passed level 2.
- If passed, show the matched APIs.
4. Check if the APK passed level 3.
- If passed, show the matched API combinations.
5. Check if the APK passed level 4.
- If passed, show the matched API sequences.
6. Check if the APK passed level 5.
- If passed, show the matched API sequences that use the same register.
```
Here is the flowchart of ``show_detail_report``.
**The code of …

Add method reference for show_detail_report in the document

---

docs/source/visual_quark_script_program.rst

We structure the website into five distinct sections, which are as follows:
1. At the top area, the navigation bar displays links to documents and social media accounts.
2. On the top right, you can fine-tune the parameters of the APIs.
3. In the bottom right, you can copy the resulting program and run it on your computer.
4. In the center, you can seamlessly drag and assemble Quark Script APIs from the left.
5. On the left area, you can select a CWE example as a template and choose Quark Script APIs to add.

Add website's initial design concept

---

docs/source/quark_method_reference.rst

show_call_graph
==================
**The algorithm of show_call_graph**
The function ``show_call_graph`` creates a call graph for each element in call_graph_analysis_list and displays messages to indicate progress.
Here is the process of ``show_call_graph``.
```
1. Display the message "Creating Call Graph..." in cyan color.
2. Create a call graph for each element in call_graph_analysis_list.
3. Display the message "Call Graph Completed" in green color.
```
Here is the flowchart of ``show_call_graph``.
**The code of show_call_graph**
``` python
def show_call_graph(self, output_format=None):
print_info("Creating Call Graph...")
for (
call_graph_analysis
) in self.quark_analysis.call_graph_analysis_list:
call_graph(call_graph_analysis, output_format)
print_success("Call Graph Completed")
```

Add method reference for show_call_graph in the document

---

.readthedocs.yaml
docs/requirements.txt

Set dependencies for readthedocs

---

docs/source/quark_script.rst

Fix typo in quark script for  CWE-749 and CWE-780

---

.github/workflows/smoke_test.yml
quark/core/quark.py
tests/core/test_quark.py

Fix keyword matching in fifth stage of quark analysis

---

docs/source/quark_method_reference.rst

show_comparison_graph
=======================
**The algorithm of show_comparison_graph**
The ``show_comparison_graph`` generates and displays a radar chart based on the maximum label confidence of rule labels which compares the behaviors between the designated APK samples.
```
1. The function "show_comparison_graph" takes four parameters:
- title: Text to be displayed as the chart's title.
- labels: Categories to be represented on the radar chart.
- malware_confidences: A mapping of malware identifiers to their respective lists of confidence scores.
- font_size: The textual size for the chart, defaulting to 22 if not specified.
2. Initialize the figure
- Create a blank figure object "fig" using "go.Figure()".
3. Set the layout of the figure using "fig.update_layout"
- Define the polar …
```

Add method reference for show_comparison_graph in the document

---

.github/workflows/pytest.yml

Change the source of radare2 in CI

---

docs/source/quark_method_reference.rst

**The algorithm of call_graph**
The ``call_graph`` method generates a call graph based on the two native APIs.
```
1. Check if the two methods in the call graph analysis are the native APIs.
- If NO, find the methods that call the native APIs under the two methods.
And we refer to them as wrappers.
- If YES, continue to the following steps.
2. Initialize the call graph and draw it in the following steps.
3. Draw the node representing the mutual parent function of the two native APIs.
4. Draw the nodes representing the wrappers.
5. Draw the edges representing the method calls between the wrappers.
6. Draw the nodes representing the two native APIs.  
7. Draw the edges representing the method calls from the mutual parent function to the native APIs. 
```
Here is the flowchart of …

Add the method reference for call_graph

---

Pipfile
Pipfile.lock
quark/script/ciphey.py
tests/script/test_ciphey.py

Make the importation for Ciphey optional

---

Dockerfile

Add the command `freshquark` to the Dockerfile

---

docs/source/quark_script.rst

Fix the inconsistances of formats in the docs for Quark Script

---

docs/source/organization.rst

Quark Script Team 
==================
The Quark Script Team is dedicated to the continual improvement of the Quark Script API. Our mission encompasses the development, maintenance, and enhancement of the API, documentation, and Quark Script Repo. We focus on developing methodologies for effective auditing and optimization, aiming to make the Quark Script API user-friendly, practical, and easily comprehensible for developers, contributors, and users.
Quark Script Team Operation Mechanism
--------------------------------------
Our approach integrates development, maintenance, and optimization of the Quark Script API. This comprehensive strategy covers both coding and documentation aspects.
* Code Aspect:
- Development & Maintenance: We start by focusing on the development and regular upkeep …

Add the description of the Quark Script team to the docs

---

docs/source/organization.rst

The Quark Core Library Team is responsible for developing and maintaining the core library of Quark, including developing and maintaining the Rizin-based and Radare2-based core library and defining processes for resolving core library issues. The goal is to build accurate and stable core libraries and to ensure the core libraries are continually updated. By leveraging the core libraries, Quark delivers reliable intelligence.
The team focuses on developing, maintaining, and enhancing the core libraries, with efforts in three dimensions: **issue resolution**, **steady updates**, and **new feature development**.
For **issue resolution**, they first evaluate the issue of the core library. Next, they report it to the relevant projects (Rizin, Radare2, or Quark) and push for fixes. Then, they …

Add the description of the Quark core library team to the docs

---

docs/source/quark_script.rst

This scenario seeks to find the **unsecured storage mechanism of sensitive data** in the APK file.
We analyze the definition of CWE-921 and identify its characteristics.
See [CWE-921](https://cwe.mitre.org/data/definitions/921.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-921.
First, we design a detection rule ``checkFileExistence.json`` to spot on behavior that checks if a file exists on a given storage mechanism. Then, we use API ``behaviorInstance.getParamValues()`` to get the file path. Finally, CWE-921 is found if the file path contains the keyword ``sdcard``.
```python …
```

Optimize the CWE-921 and CWE-89 document

---

docs/source/organization.rst

```Version: v1.1```
The Quark release process is as below:

Update the release timing in the document

---

.github/workflows/pytest.yml
codecov.yml

Due to Codecov CI failure with depreciated v3, this PR updates the Codecov action to v4.
**File changes**
* .github/workflows/pytest.yml
* codecov.yml

Update Codecov action to v4.

---

docs/source/quark_script.rst

This scenario seeks to find **Use of a Broken or Risky Cryptographic Algorithm** in the APK file.
We analyze the definition of CWE-327 and identify its characteristics.
See [CWE-327](https://cwe.mitre.org/data/definitions/327.html) for more details.
We use the [InjuredAndroid.apk](https://github.com/B3nac/InjuredAndroid) sample to explain the vulnerability code of CWE-327.
Quark Script CWE-327.py
===========================
We first design a detection rule `useOfCryptographicAlgo.json` to spot on behavior using cryptographic algorithms. Then, we use API `behaviorInstance.hasString(pattern, isRegex)` with a list to check if the algorithm is risky. If YES, that may cause the exposure of sensitive data.
```python …
```

Optimize CWE-327 document

---

.github/workflows/smoke_test.yml

This PR aims to set the Mac OS version in smoke test with Mac OS 13.

Fix the CI failure with the Mac OS smoke test.

---

codecov.yml

Add the threshold in codecov.yml.

---

README.md

Update the badges in the README.md

---

Pipfile
Pipfile.lock
docs/requirements.txt

Update dependency versions in pipenv environment

---

README.md

<p align="center">
<a href="https://www.blackhat.com/asia-24/arsenal/schedule/index.html#quark-script---dig-vulnerabilities-in-the-blackbox-37549">
</a>
<a href="https://www.blackhat.com/asia-21/arsenal/schedule/index.html#quark-engine-storyteller-of-android-malware-22458">
</a>
<a href="https://conference.hitb.org/hitb-lockdown002/sessions/quark-engine-an-obfuscation-neglect-android-malware-scoring-system/">
</a>
<a href="https://www.youtube.com/watch?v=XK-yqHPnsvc&ab_channel=DEFCONConference">
</a><br>
<a href="https://github.com/quark-engine/quark-engine/actions/workflows/pytest.yml">
</a>
<a href="https://codecov.io/gh/quark-engine/quark-engine">
</a>
<a href="https://github.com/18z/quark-rules/blob/master/LICENSE">
</a>
<a href="https://www.python.org/downloads/release/python-360/"> …

Add Quark Agent workflow feature preview to README

---

README.md

To stay updated with the latest news, make sure to watch our GitHub repository and follow us on [X (Twitter)](https://twitter.com/quarkengine).

Add 'Stay Connected' section to README.md

---

README.md

<p align="center">
<a href="https://www.blackhat.com/asia-24/arsenal/schedule/index.html#quark-script---dig-vulnerabilities-in-the-blackbox-37549">
</a>
<a href="https://www.blackhat.com/asia-21/arsenal/schedule/index.html#quark-engine-storyteller-of-android-malware-22458">
</a>
<a href="https://conference.hitb.org/hitb-lockdown002/sessions/quark-engine-an-obfuscation-neglect-android-malware-scoring-system/">
</a>
<a href="https://www.youtube.com/watch?v=XK-yqHPnsvc&ab_channel=DEFCONConference">
</a><br>
<a href="https://github.com/quark-engine/quark-engine/actions/workflows/pytest.yml">
</a>
<a href="https://codecov.io/gh/quark-engine/quark-engine">
</a>
<a href="https://github.com/18z/quark-rules/blob/master/LICENSE">
</a>
<a href="https://www.python.org/downloads/release/python-360/"> …

Add Quark Agent's Auto-Suggestion preview to README

---

docs/source/quark_script.rst

This scenario seeks to find **insertion of sensitive information into Log file** in the APK file.
We analyze the definition of CWE-532 and identify its characteristics.
See [CWE-532](https://cwe.mitre.org/data/definitions/532.html) for more details.
Code of CWE-532 in dvba.apk
We use the [dvba.apk](https://github.com/rewanthtammana/Damn-Vulnerable-Bank)  sample to explain the vulnerability code of CWE-532.
Quark Scipt: CWE-532.py
First, we use the API ``findMethodInAPK(samplePath, targetMethod)`` to locate ``log.d`` method. Then we use API ``methodInstance.getArguments()`` to get the argument that input to ``log.d``. Finally, we use some …

Optimize the document of Quark Script CWE-532

---

.github/workflows/pytest.yml

Update radare2 version to 5.9.0 in CI

---

.github/workflows/pytest.yml
.github/workflows/smoke_test.yml
Pipfile
Pipfile.lock
quark/core/axmlreader/__init__.py
quark/script/frida/__init__.py
quark/utils/output.py
quark/webreport/generate.py
tests/webreport/test_generate.py

This PR aims to solve issue #701 and #710 .

Replace deprecated package and change syntax to solve issues in python 3.12

---

docs/source/quark_script.rst

This scenario seeks to find the **unsecured storage mechanism of sensitive data** in the APK file.
We analyze the definition of CWE-921 and identify its characteristics.
See [CWE-921](https://cwe.mitre.org/data/definitions/921.html) for more details.
We use the [ovaa.apk](https://github.com/oversecured/ovaa) sample to explain the vulnerability code of CWE-921.
First, we design a detection rule ``checkFileExistence.json`` to spot on behavior that checks if a file exists on a given storage mechanism. Then, we use API ``methodInstance.getArguments()`` to get the file path. Finally, CWE-921 is found if the file path contains the keyword ``sdcard``.
```python …
```

Optimize the document of Quark Script CWE-921

---

docs/source/quark_script.rst

This scenario seeks to find **Improper Input Validation** in the APK file.
We analyze the definition of CWE-20 and identify its characteristics.
See [CWE-20](https://cwe.mitre.org/data/definitions/20.html) for more details.
We use the [diva.apk](https://github.com/payatu/diva-android) sample to explain the vulnerability code of CWE-20.
First, we design a detection rule ``openUrlThatUserInput.json``, to spot the behavior of opening the URL that the user inputs. Then, we use API ``behaviorInstance.getMethodsInArgs()`` to get a list of methods that the URL in ``loadUrl`` passes through. Finally, we check if any validation method is in the list. If No, the APK does not validate user input. That causes CWE-20 …

Optimize the document of Quark Script CWE-20

---

docs/source/quark_script.rst

This scenario seeks to find **SQL injection** in the APK file.
We analyze the definition of CWE-89 and identify its characteristics.
See [CWE-89](https://cwe.mitre.org/data/definitions/89.html) for more details.
We use the [AndroGoat.apk](https://github.com/satishpatnayak/AndroGoat) sample to explain the vulnerability code of CWE-89.
First, we design a detection rule `executeSQLCommand.json` to spot on behavior using SQL command Execution. Then, we use API `behaviorInstance.isArgFromMethod(targetMethod)` to check if `append` uses the value of `getText` as the argument. If yes, we confirmed that the SQL command string is built from user input, which will cause CWE-89 vulnerability.
```python
from quark.script …
```

Optimize the document of Quark Script CWE-89

---

quark/core/shurikenapkinfo.py

Change decorator of all_methods in Shuriken core to optimize performance

---

docs/source/quark_script.rst

This scenario seeks to find **Improper Certificate Validation**.
We analyze the definition of CWE-295 and identify its characteristics.
See [CWE-295](https://cwe.mitre.org/data/definitions/295.html) for more details.
We use the [InsecureShop.apk](https://github.com/hax0rgb/InsecureShop) sample to explain the vulnerability code of CWE-295.
To begin with, we use the API ``findMethodInAPK(samplePath, targetMethod)`` to locate all callers of method ``SslErrorHandler.proceed``.
Next, we must verify whether the caller overrides the method ``WebViewClient.onReceivedSslError``.
Therefore, we check if the caller has the same method name and descriptor as ``WebViewClient.onReceivedSslError``, then use ``findSuperclassHierarchy()`` to see if its class extends ``Landroid/webkit/WebViewClient``.
If …

Optimize the document of Quark Script CWE-295

---

Pipfile
quark/utils/graph.py
setup.py
tests/utils/test_graph.py

Fix file name error while creating call graphs

---

.github/workflows/smoke_test.yml

Update the expected result for Quark analysis in the smoke test

---

quark/core/quark.py

Round the total score to an integer in the Quark report
